# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'vs2015-win2012r2'


steps:
- task: UseNode@1
  displayName: 'Use Node '
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'tin-drink'

- task: CmdLine@2
  inputs:
    script: 'npm i -g eslint'
    workingDirectory: 'tin-drink'

    
- task: CmdLine@2
  inputs:
    script: 'dir'

- task: CmdLine@1
  displayName: 'Run git diff changes'
  inputs:
    filename: echo
    arguments: '$(System.PullRequest.PullRequestNumber)'

- task: PowerShell@2
  inputs:
    filePath: 'pullid.ps1'
    arguments: '-pullNumber $(Build.SourceVersion)'

- task: CmdLine@2
  inputs:
    script: 'dir /S'
    workingDirectory: 'tin-drink'
    
- task: CmdLine@2
  inputs:
    script: 'eslint --max-warnings 1000 src/**.js '
    workingDirectory: 'tin-drink'


- task: CmdLine@2
  inputs:
    script: 'eslint .\changedFiles\**\*.js -o ..\eslint.json -f json || ver>nul'
    workingDirectory: 'tin-drink'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo printenv'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'tin-drink'
- task: CmdLine@2
  inputs:
    script: 'sudo npm install -g eslint'
    workingDirectory: 'tin-drink'
- task: CmdLine@2
  inputs:
    script: 'sudo npm install eslint-plugin-import@latest --save-dev'
    workingDirectory: 'tin-drink'

- task: CmdLine@2
  inputs:
    script: 'sudo eslint src/*.js -o tst.json -f json || true'
    workingDirectory: 'tin-drink'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'tin-drink/tst.json'
    ArtifactName: 'drop'
    publishLocation: 'Container'
